export type Question = {
  id: number
  block: 'messi' | 'empresa' | 'verdadero_falso'
  blockLabel: string
  type: 'multiple' | 'truefalse'
  question: string
  options: string[]
  correct: number // índice de la respuesta correcta
  timeLimit: number // segundos
}

export const QUESTIONS: Question[] = [
  // ── BLOQUE 1: MESSI ──────────────────────────────────────────
  {
    id: 1,
    block: 'messi',
    blockLabel: '⚽ Bloque Messi',
    type: 'multiple',
    question: '¿En qué ciudad nació Lionel Messi?',
    options: ['Buenos Aires', 'Rosario', 'Córdoba', 'Mendoza'],
    correct: 1,
    timeLimit: 20,
  },
  {
    id: 2,
    block: 'messi',
    blockLabel: '⚽ Bloque Messi',
    type: 'multiple',
    question: '¿Cuántos Balones de Oro ganó Messi hasta 2023?',
    options: ['6', '7', '8', '9'],
    correct: 2,
    timeLimit: 20,
  },
  {
    id: 3,
    block: 'messi',
    blockLabel: '⚽ Bloque Messi',
    type: 'multiple',
    question: '¿A qué edad debutó Messi en la primera del Barcelona?',
    options: ['15', '16', '17', '18'],
    correct: 2,
    timeLimit: 20,
  },
  {
    id: 4,
    block: 'messi',
    blockLabel: '⚽ Bloque Messi',
    type: 'multiple',
    question: '¿Cuántos goles marcó Messi en la temporada récord 2011/12?',
    options: ['73', '91', '86', '79'],
    correct: 1,
    timeLimit: 20,
  },
  {
    id: 5,
    block: 'messi',
    blockLabel: '⚽ Bloque Messi',
    type: 'multiple',
    question: '¿En qué año ganó Argentina el Mundial con Messi como capitán?',
    options: ['2018', '2021', '2022', '2023'],
    correct: 2,
    timeLimit: 20,
  },

  // ── BLOQUE 2: EMPRESA (ficticios — cambiá por los reales) ─────
  {
    id: 6,
    block: 'empresa',
    blockLabel: '🏢 Bloque Empresa',
    type: 'multiple',
    question: '¿En qué año fue fundada la empresa?',
    options: ['2005', '2008', '2010', '2015'],
    correct: 1,
    timeLimit: 25,
  },
  {
    id: 7,
    block: 'empresa',
    blockLabel: '🏢 Bloque Empresa',
    type: 'multiple',
    question: '¿En cuántos países opera la empresa actualmente?',
    options: ['3', '5', '8', '12'],
    correct: 2,
    timeLimit: 25,
  },
  {
    id: 8,
    block: 'empresa',
    blockLabel: '🏢 Bloque Empresa',
    type: 'multiple',
    question: '¿Cuál es el valor principal que define la cultura de la empresa?',
    options: ['Velocidad', 'Innovación', 'Confianza', 'Eficiencia'],
    correct: 1,
    timeLimit: 25,
  },
  {
    id: 9,
    block: 'empresa',
    blockLabel: '🏢 Bloque Empresa',
    type: 'multiple',
    question: '¿Cuántos empleados tiene la empresa aproximadamente?',
    options: ['50', '150', '300', '500'],
    correct: 1,
    timeLimit: 25,
  },
  {
    id: 10,
    block: 'empresa',
    blockLabel: '🏢 Bloque Empresa',
    type: 'multiple',
    question: '¿Cuál fue el primer producto o servicio que lanzó la empresa?',
    options: ['Consultoría', 'Software propio', 'E-commerce', 'App mobile'],
    correct: 1,
    timeLimit: 25,
  },

  // ── BLOQUE 3: VERDADERO O FALSO ──────────────────────────────
  {
    id: 11,
    block: 'verdadero_falso',
    blockLabel: '🔥 Verdadero o Falso',
    type: 'truefalse',
    question: 'En programación, un bug es un error en el código.',
    options: ['Verdadero', 'Falso'],
    correct: 0,
    timeLimit: 15,
  },
  {
    id: 12,
    block: 'verdadero_falso',
    blockLabel: '🔥 Verdadero o Falso',
    type: 'truefalse',
    question: 'El flujo de caja negativo siempre significa que una empresa pierde dinero.',
    options: ['Verdadero', 'Falso'],
    correct: 1,
    timeLimit: 15,
  },
  {
    id: 13,
    block: 'verdadero_falso',
    blockLabel: '🔥 Verdadero o Falso',
    type: 'truefalse',
    question: 'RRHH solo se encarga de contratar y despedir personas.',
    options: ['Verdadero', 'Falso'],
    correct: 1,
    timeLimit: 15,
  },
  {
    id: 14,
    block: 'verdadero_falso',
    blockLabel: '🔥 Verdadero o Falso',
    type: 'truefalse',
    question: 'Git es una herramienta de control de versiones de código.',
    options: ['Verdadero', 'Falso'],
    correct: 0,
    timeLimit: 15,
  },
  {
    id: 15,
    block: 'verdadero_falso',
    blockLabel: '🔥 Verdadero o Falso',
    type: 'truefalse',
    question: 'El EBITDA incluye los intereses e impuestos de una empresa.',
    options: ['Verdadero', 'Falso'],
    correct: 1,
    timeLimit: 15,
  },
  {
    id: 16,
    block: 'verdadero_falso',
    blockLabel: '🔥 Verdadero o Falso',
    type: 'truefalse',
    question: 'Una API es una interfaz que permite comunicar dos sistemas.',
    options: ['Verdadero', 'Falso'],
    correct: 0,
    timeLimit: 15,
  },
  {
    id: 17,
    block: 'verdadero_falso',
    blockLabel: '🔥 Verdadero o Falso',
    type: 'truefalse',
    question: 'El onboarding de un empleado termina el primer día de trabajo.',
    options: ['Verdadero', 'Falso'],
    correct: 1,
    timeLimit: 15,
  },
  {
    id: 18,
    block: 'verdadero_falso',
    blockLabel: '🔥 Verdadero o Falso',
    type: 'truefalse',
    question: 'Una deuda tiene siempre un impacto negativo en las finanzas de una empresa.',
    options: ['Verdadero', 'Falso'],
    correct: 1,
    timeLimit: 15,
  },
  {
    id: 19,
    block: 'verdadero_falso',
    blockLabel: '🔥 Verdadero o Falso',
    type: 'truefalse',
    question: 'En Scrum, el Sprint dura exactamente 1 mes siempre.',
    options: ['Verdadero', 'Falso'],
    correct: 1,
    timeLimit: 15,
  },
  {
    id: 20,
    block: 'verdadero_falso',
    blockLabel: '🔥 Verdadero o Falso',
    type: 'truefalse',
    question: 'El balance general muestra los resultados de una empresa en un período.',
    options: ['Verdadero', 'Falso'],
    correct: 1,
    timeLimit: 15,
  },
]

export const BLOCKS = [
  { key: 'messi', label: '⚽ Bloque Messi', range: [1, 5] },
  { key: 'empresa', label: '🏢 Bloque Empresa', range: [6, 10] },
  { key: 'verdadero_falso', label: '🔥 Verdadero o Falso', range: [11, 20] },
]
