export type Question = {
  id: number
  block: 'messi' | 'empresa' | 'nerd'
  blockLabel: string
  type: 'multiple' | 'truefalse'
  question: string
  options: string[]
  correct: number // índice de la respuesta correcta
  timeLimit: number // segundos
}

export const QUESTIONS: Question[] = [
  // ── BLOQUE 1: MESSI ──────────────────────────────────────────
  {
    id: 1,
    block: 'messi',
    blockLabel: '👑 Conociendo a nuestro capitán',
    type: 'multiple',
    question: '¿En qué ciudad nació Lionel Messi?',
    options: ['Buenos Aires', 'Rosario', 'Córdoba', 'Mendoza'],
    correct: 1,
    timeLimit: 20,
  },
  {
    id: 2,
    block: 'messi',
    blockLabel: '👑 Conociendo a nuestro capitán',
    type: 'multiple',
    question: 'En su debut absoluto con la Selección mayor (2005 vs Hungría), ¿qué pasó?',
    options: ['Hizo un gol', 'Dio una asistencia', 'Fue expulsado a los pocos minutos', 'Erró un penal'],
    correct: 2,
    timeLimit: 20,
  },
  {
    id: 3,
    block: 'messi',
    blockLabel: '👑 Conociendo a nuestro capitán',
    type: 'multiple',
    question: '¿En qué Mundial debutó Messi con la Selección mayor?',
    options: ['2010 (Sudáfrica)', '2006 (Alemania)', '2014 (Brasil)', '2018 (Rusia)'],
    correct: 1,
    timeLimit: 20,
  },
  {
    id: 4,
    block: 'messi',
    blockLabel: '👑 Conociendo a nuestro capitán',
    type: 'multiple',
    question: '¿Contra qué país hizo Messi su primer gol en un Mundial?',
    options: ['México', 'Serbia y Montenegro', 'Nigeria', 'Alemania'],
    correct: 1,
    timeLimit: 20,
  },
  {
    id: 5,
    block: 'messi',
    blockLabel: '👑 Conociendo a nuestro capitán',
    type: 'multiple',
    question: '¿En qué año ganó Argentina el Mundial con Messi como capitán?',
    options: ['2018', '2021', '2022', '2023'],
    correct: 2,
    timeLimit: 20,
  },

  // ── BLOQUE 2: EMPRESA (ficticios — cambiá por los reales) ─────
  {
    id: 6,
    block: 'empresa',
    blockLabel: '🏢 Bloque Empresa',
    type: 'multiple',
    question: '¿Cuántos años tiene HMM?',
    options: ['4', '5', '6', '7'],
    correct: 2,
    timeLimit: 20,
  },
  {
    id: 7,
    block: 'empresa',
    blockLabel: '🏢 Bloque Empresa',
    type: 'multiple',
    question: '¿Cuántas personas trabajan actualmente en HMM?',
    options: ['33', '51', '35', '42'],
    correct: 2,
    timeLimit: 20,
  },
  {
    id: 8,
    block: 'empresa',
    blockLabel: '🏢 Bloque Empresa',
    type: 'multiple',
    question: '¿Qué día cumple años HMM?',
    options: ['30 de octubre', '27 de septiembre', '2 de Noviembre', '27 de octubre'],
    correct: 0,
    timeLimit: 20,
  },
  {
    id: 9,
    block: 'empresa',
    blockLabel: '🏢 Bloque Empresa',
    type: 'multiple',
    question: '¿Con qué herramienta se hizo el primer logo?',
    options: ['Corel', 'Photoshop', 'Portaminas', 'Paint'],
    correct: 3,
    timeLimit: 20,
  },
  {
    id: 10,
    block: 'empresa',
    blockLabel: '🏢 Bloque Empresa',
    type: 'multiple',
    question: '¿Cuál fué la primer oficina de HMM?',
    options: ['Garage de DG', 'Fernando Fader Office', 'Juan Castagnino', 'Coworking Centro CBA'],
    correct: 1,
    timeLimit: 20,
  },

  // ── BLOQUE 3: NERD RANDOM 🤓 ─────────────────────────────────
  {
    id: 11,
    block: 'nerd',
    blockLabel: '🤓 Nerd Random',
    type: 'multiple',
    question: '¿Cómo se llama el perro de los Simpson?',
    options: ['Bola de Nieve', 'Pequeño Ayudante de Santa Claus', 'Rex', 'Ayudante'],
    correct: 1,
    timeLimit: 20,
  },
  {
    id: 12,
    block: 'nerd',
    blockLabel: '🤓 Nerd Random',
    type: 'multiple',
    question: 'El lenguaje de programación Python fue nombrado en honor a…',
    options: ['Una serpiente', 'Monty Python (comediantes)', 'Su creador, Python', 'Una galaxia'],
    correct: 1,
    timeLimit: 20,
  },
  {
    id: 13,
    block: 'nerd',
    blockLabel: '🤓 Nerd Random',
    type: 'multiple',
    question: 'Sin ajustar por inflación, ¿cuál es la película más taquillera de la historia?',
    options: ['Avengers: Endgame', 'Titanic', 'Avatar', 'Star Wars'],
    correct: 2,
    timeLimit: 20,
  },
  {
    id: 14,
    block: 'nerd',
    blockLabel: '🤓 Nerd Random',
    type: 'multiple',
    question: '¿Cuántos corazones tiene un pulpo?',
    options: ['1', '2', '3', '5'],
    correct: 2,
    timeLimit: 20,
  },
  {
    id: 15,
    block: 'nerd',
    blockLabel: '🤓 Nerd Random',
    type: 'multiple',
    question: 'El primer "bug" informático real (1947) fue causado por…',
    options: ['Una araña', 'Una polilla', 'Una cucaracha', 'Un virus'],
    correct: 1,
    timeLimit: 20,
  },
  {
    id: 16,
    block: 'nerd',
    blockLabel: '🤓 Nerd Random',
    type: 'multiple',
    question: '¿A qué velocidad puede salir un estornudo?',
    options: ['~76 km/h', '~90 km/h', '~160 km/h', '~210 km/h'],
    correct: 2,
    timeLimit: 20,
  },
  {
    id: 17,
    block: 'nerd',
    blockLabel: '🤓 Nerd Random',
    type: 'multiple',
    question: 'En la web, el error "404" significa…',
    options: ['Acceso denegado', 'Página no encontrada', 'Error del servidor', 'Sesión expirada'],
    correct: 1,
    timeLimit: 20,
  },
  {
    id: 18,
    block: 'nerd',
    blockLabel: '🤓 Nerd Random',
    type: 'multiple',
    question: '¿Cuántos dientes puede tener un caracol?',
    options: ['Ninguno', '32', '500', 'Más de 10.000'],
    correct: 3,
    timeLimit: 20,
  },
  {
    id: 19,
    block: 'nerd',
    blockLabel: '🤓 Nerd Random',
    type: 'multiple',
    question: 'Según la ciencia (evolución), ¿qué fue primero?',
    options: ['La gallina', 'El huevo', 'Al mismo tiempo', 'Nadie lo sabe'],
    correct: 1,
    timeLimit: 20,
  },
  {
    id: 20,
    block: 'nerd',
    blockLabel: '🤓 Nerd Random',
    type: 'multiple',
    question: '¿Qué animal es incapaz de saltar?',
    options: ['El canguro', 'El elefante', 'La rana', 'El gato'],
    correct: 1,
    timeLimit: 20,
  },
]

export const BLOCKS = [
  { key: 'messi', label: '👑 Conociendo a nuestro capitán', range: [1, 5] },
  { key: 'empresa', label: '🏢 Bloque Empresa', range: [6, 10] },
  { key: 'nerd', label: '🤓 Nerd Random', range: [11, 20] },
]
